### ISSUE TITLE
 Diseño de los cards de eventos

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/decidim-eventos#1]
Según lo sugerido, implementar el diseño de los cards. 

Pero verificar que también se quería con imágenes: 

> "Acá con Juanca estamos tratando de mejorar la vista a algo así, pero que además incluya thumbnails"

![3_960](https://user-images.githubusercontent.com/6553005/41109995-58af611a-6a46-11e8-8dc7-d5c2b733907b.jpg)

También tiene que aparecer la imagen asociada al evento

Issue migrado de https://github.com/TEDICpy/miciudad2/issues/39

**Comment by yank07** [comment]
Este tema ya se hizo, Juanca al final me paso otro diseño que es el que esta publicado ahora.

**Comment by lupa18** [comment]
Creo que tiene un pequeño error que hoy viste y aparece cuando ves muchos eventos: https://beta.encarnacion.org.py/rendezvouses?utf8=%E2%9C%93&filter%5Bsearch_text%5D=&filter%5Bdate%5D=&filter%5Bdate%5D=past

**Comment by lupa18** [comment]
Quedó bien el layout en general. Ahora el problema es con las imágenes que no se dimensionan bien: 

![seleccion_646](https://user-images.githubusercontent.com/463429/44422802-25825580-a552-11e8-8159-ff4255182372.png)
