### ISSUE TITLE
Idioma de fecha y hora al crear evento sale en inglés

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/decidim-eventos#3]
Tanto la representación dentro del casillero, como el pop-up. 

Debería ser en español: 

![seleccion_595](https://user-images.githubusercontent.com/463429/42293122-c1d60864-7fa5-11e8-84dd-4350d017bc65.png)

**Comment by diegocrzt** [comment]
En #55 se fuerza la localización a español.
